# Generated by Django 3.1.12 on 2025-02-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('stock_status', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('availability', models.CharField(max_length=50)),
            ],
        ),
    ]
